### ISSUE TITLE
Error in Week-7 Code

### ISSUE THREAD

**Issue by rishabh-shrivastava** [biodunalfet/Control-Of-Mobile-Robots#1]
Hi there,

There is some error in the code of Week-7. If you change the positions of goal in QBSupervisor.m from [1.1,1.1] to anything else, robot either collides or keeps circling middle obstacle.
![image](https://cloud.githubusercontent.com/assets/17477859/20698269/ebd44eaa-b625-11e6-891e-c2701211aea2.png)

**Comment by biodunalfet** [comment]
Okay. Been a while I did this, but I'll try run it on my computer and get back to you

**Comment by rishabh-shrivastava** [comment]
Yeah, sure. It is very important for me to get the correct code. Please
help.

**Comment by rishabh-shrivastava** [comment]
obj.fw_direction  = 'left';
When I change this statement to obj.fw_direction   = 'right'; it collides
with the upper wall. (QBSupervisor.m)
